version: "3.9"
services:
  db:
    image: postgres:15
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: me
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: portfolio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
