name: API tests

on:
  pull_request:
    paths:
      - "api/**"
  push:
    branches:
      - main
      - feature/unit-tests

jobs:
  test-api:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: api
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: me
          POSTGRES_PASSWORD: cascava1
          POSTGRES_DB: portfolio_test
        ports:
          - 5435:5432
        options: >-
          --health-cmd "pg_isready -U me -d portfolio_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Wait for Postgres
        run: |
          for i in {1..15}; do
            pg_isready -h localhost -p 5435 -U me && break
            sleep 2
          done

      - name: Run migrations
        env:
          DATABASE_URL: postgresql://me:cascava1@localhost:5435/portfolio_test
        run: npx prisma migrate deploy

      - name: Run tests
        env:
          DATABASE_URL: postgresql://me:cascava1@localhost:5435/portfolio_test
        run: npm test --silent
