name: CI — web tests

on:
  push:
    paths:
      - "web/**"
  pull_request:
    paths:
      - "web/**"

jobs:
  web-tests:
    name: Run web tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install dependencies in web/
        working-directory: ./web
        run: npm ci

      - name: Run tests
        working-directory: ./web
        run: npm test --silent
